micronaut:
  application:
    name: agentSidecar
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
netty:
  default:
    allocator:
      max-order: 3
rabbitmq.uri: ${RABBIT_MQ_ADDRESS}


agent.uniqueName: ${AGENT_UNIQUE_NAME}
messagebox.exchange: ${MESSAGE_BOX_EXCHANGE}
messagebox.jobs.queue: ${MESSAGE_BOX_JOBS_QUEUE}

jobs.descriptions: ${JOBS_DESCRIPTIONS_FOLDER}
jobs.outputs: ${JOBS_OUTPUTS_FOLDER}
job.script.path: ${JOB_SCRIPT_PATH}
ephemeral: ${EPHEMERAL}
rabbitmq:
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}